language: node_js
sudo: false
node_js:
  - '12'
env:
  global:
    - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
install:
  - npm install --global npm@6.x.x
  - npm ci
