// flow-typed signature: 0c8116748b2d73bdef44ab2d201b6e90
// flow-typed version: <<STUB>>/amazon-cognito-auth-js_v1.2.4/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'amazon-cognito-auth-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'amazon-cognito-auth-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'amazon-cognito-auth-js/dist/amazon-cognito-auth' {
  declare module.exports: any;
}

declare module 'amazon-cognito-auth-js/dist/amazon-cognito-auth.min' {
  declare module.exports: any;
}

declare module 'amazon-cognito-auth-js/dist/aws-cognito-sdk' {
  declare module.exports: any;
}

declare module 'amazon-cognito-auth-js/dist/aws-cognito-sdk.min' {
  declare module.exports: any;
}

declare module 'amazon-cognito-auth-js/enhance' {
  declare module.exports: any;
}

declare module 'amazon-cognito-auth-js/es/CognitoAccessToken' {
  declare module.exports: any;
}

declare module 'amazon-cognito-auth-js/es/CognitoAuth' {
  declare module.exports: any;
}

declare module 'amazon-cognito-auth-js/es/CognitoAuthSession' {
  declare module.exports: any;
}

declare module 'amazon-cognito-auth-js/es/CognitoIdToken' {
  declare module.exports: any;
}

declare module 'amazon-cognito-auth-js/es/CognitoRefreshToken' {
  declare module.exports: any;
}

declare module 'amazon-cognito-auth-js/es/CognitoTokenScopes' {
  declare module.exports: any;
}

declare module 'amazon-cognito-auth-js/es/CookieStorage' {
  declare module.exports: any;
}

declare module 'amazon-cognito-auth-js/es/DateHelper' {
  declare module.exports: any;
}

declare module 'amazon-cognito-auth-js/es' {
  declare module.exports: any;
}

declare module 'amazon-cognito-auth-js/es/StorageHelper' {
  declare module.exports: any;
}

declare module 'amazon-cognito-auth-js/lib/CognitoAccessToken' {
  declare module.exports: any;
}

declare module 'amazon-cognito-auth-js/lib/CognitoAuth' {
  declare module.exports: any;
}

declare module 'amazon-cognito-auth-js/lib/CognitoAuthSession' {
  declare module.exports: any;
}

declare module 'amazon-cognito-auth-js/lib/CognitoIdToken' {
  declare module.exports: any;
}

declare module 'amazon-cognito-auth-js/lib/CognitoRefreshToken' {
  declare module.exports: any;
}

declare module 'amazon-cognito-auth-js/lib/CognitoTokenScopes' {
  declare module.exports: any;
}

declare module 'amazon-cognito-auth-js/lib/CookieStorage' {
  declare module.exports: any;
}

declare module 'amazon-cognito-auth-js/lib/DateHelper' {
  declare module.exports: any;
}

declare module 'amazon-cognito-auth-js/lib' {
  declare module.exports: any;
}

declare module 'amazon-cognito-auth-js/lib/StorageHelper' {
  declare module.exports: any;
}

declare module 'amazon-cognito-auth-js/src/CognitoAccessToken' {
  declare module.exports: any;
}

declare module 'amazon-cognito-auth-js/src/CognitoAuth' {
  declare module.exports: any;
}

declare module 'amazon-cognito-auth-js/src/CognitoAuthSession' {
  declare module.exports: any;
}

declare module 'amazon-cognito-auth-js/src/CognitoIdToken' {
  declare module.exports: any;
}

declare module 'amazon-cognito-auth-js/src/CognitoRefreshToken' {
  declare module.exports: any;
}

declare module 'amazon-cognito-auth-js/src/CognitoTokenScopes' {
  declare module.exports: any;
}

declare module 'amazon-cognito-auth-js/src/CookieStorage' {
  declare module.exports: any;
}

declare module 'amazon-cognito-auth-js/src/DateHelper' {
  declare module.exports: any;
}

declare module 'amazon-cognito-auth-js/src' {
  declare module.exports: any;
}

declare module 'amazon-cognito-auth-js/src/StorageHelper' {
  declare module.exports: any;
}

declare module 'amazon-cognito-auth-js/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'amazon-cognito-auth-js/dist/amazon-cognito-auth.js' {
  declare module.exports: $Exports<'amazon-cognito-auth-js/dist/amazon-cognito-auth'>;
}
declare module 'amazon-cognito-auth-js/dist/amazon-cognito-auth.min.js' {
  declare module.exports: $Exports<'amazon-cognito-auth-js/dist/amazon-cognito-auth.min'>;
}
declare module 'amazon-cognito-auth-js/dist/aws-cognito-sdk.js' {
  declare module.exports: $Exports<'amazon-cognito-auth-js/dist/aws-cognito-sdk'>;
}
declare module 'amazon-cognito-auth-js/dist/aws-cognito-sdk.min.js' {
  declare module.exports: $Exports<'amazon-cognito-auth-js/dist/aws-cognito-sdk.min'>;
}
declare module 'amazon-cognito-auth-js/enhance.js' {
  declare module.exports: $Exports<'amazon-cognito-auth-js/enhance'>;
}
declare module 'amazon-cognito-auth-js/es/CognitoAccessToken.js' {
  declare module.exports: $Exports<'amazon-cognito-auth-js/es/CognitoAccessToken'>;
}
declare module 'amazon-cognito-auth-js/es/CognitoAuth.js' {
  declare module.exports: $Exports<'amazon-cognito-auth-js/es/CognitoAuth'>;
}
declare module 'amazon-cognito-auth-js/es/CognitoAuthSession.js' {
  declare module.exports: $Exports<'amazon-cognito-auth-js/es/CognitoAuthSession'>;
}
declare module 'amazon-cognito-auth-js/es/CognitoIdToken.js' {
  declare module.exports: $Exports<'amazon-cognito-auth-js/es/CognitoIdToken'>;
}
declare module 'amazon-cognito-auth-js/es/CognitoRefreshToken.js' {
  declare module.exports: $Exports<'amazon-cognito-auth-js/es/CognitoRefreshToken'>;
}
declare module 'amazon-cognito-auth-js/es/CognitoTokenScopes.js' {
  declare module.exports: $Exports<'amazon-cognito-auth-js/es/CognitoTokenScopes'>;
}
declare module 'amazon-cognito-auth-js/es/CookieStorage.js' {
  declare module.exports: $Exports<'amazon-cognito-auth-js/es/CookieStorage'>;
}
declare module 'amazon-cognito-auth-js/es/DateHelper.js' {
  declare module.exports: $Exports<'amazon-cognito-auth-js/es/DateHelper'>;
}
declare module 'amazon-cognito-auth-js/es/index' {
  declare module.exports: $Exports<'amazon-cognito-auth-js/es'>;
}
declare module 'amazon-cognito-auth-js/es/index.js' {
  declare module.exports: $Exports<'amazon-cognito-auth-js/es'>;
}
declare module 'amazon-cognito-auth-js/es/StorageHelper.js' {
  declare module.exports: $Exports<'amazon-cognito-auth-js/es/StorageHelper'>;
}
declare module 'amazon-cognito-auth-js/lib/CognitoAccessToken.js' {
  declare module.exports: $Exports<'amazon-cognito-auth-js/lib/CognitoAccessToken'>;
}
declare module 'amazon-cognito-auth-js/lib/CognitoAuth.js' {
  declare module.exports: $Exports<'amazon-cognito-auth-js/lib/CognitoAuth'>;
}
declare module 'amazon-cognito-auth-js/lib/CognitoAuthSession.js' {
  declare module.exports: $Exports<'amazon-cognito-auth-js/lib/CognitoAuthSession'>;
}
declare module 'amazon-cognito-auth-js/lib/CognitoIdToken.js' {
  declare module.exports: $Exports<'amazon-cognito-auth-js/lib/CognitoIdToken'>;
}
declare module 'amazon-cognito-auth-js/lib/CognitoRefreshToken.js' {
  declare module.exports: $Exports<'amazon-cognito-auth-js/lib/CognitoRefreshToken'>;
}
declare module 'amazon-cognito-auth-js/lib/CognitoTokenScopes.js' {
  declare module.exports: $Exports<'amazon-cognito-auth-js/lib/CognitoTokenScopes'>;
}
declare module 'amazon-cognito-auth-js/lib/CookieStorage.js' {
  declare module.exports: $Exports<'amazon-cognito-auth-js/lib/CookieStorage'>;
}
declare module 'amazon-cognito-auth-js/lib/DateHelper.js' {
  declare module.exports: $Exports<'amazon-cognito-auth-js/lib/DateHelper'>;
}
declare module 'amazon-cognito-auth-js/lib/index' {
  declare module.exports: $Exports<'amazon-cognito-auth-js/lib'>;
}
declare module 'amazon-cognito-auth-js/lib/index.js' {
  declare module.exports: $Exports<'amazon-cognito-auth-js/lib'>;
}
declare module 'amazon-cognito-auth-js/lib/StorageHelper.js' {
  declare module.exports: $Exports<'amazon-cognito-auth-js/lib/StorageHelper'>;
}
declare module 'amazon-cognito-auth-js/src/CognitoAccessToken.js' {
  declare module.exports: $Exports<'amazon-cognito-auth-js/src/CognitoAccessToken'>;
}
declare module 'amazon-cognito-auth-js/src/CognitoAuth.js' {
  declare module.exports: $Exports<'amazon-cognito-auth-js/src/CognitoAuth'>;
}
declare module 'amazon-cognito-auth-js/src/CognitoAuthSession.js' {
  declare module.exports: $Exports<'amazon-cognito-auth-js/src/CognitoAuthSession'>;
}
declare module 'amazon-cognito-auth-js/src/CognitoIdToken.js' {
  declare module.exports: $Exports<'amazon-cognito-auth-js/src/CognitoIdToken'>;
}
declare module 'amazon-cognito-auth-js/src/CognitoRefreshToken.js' {
  declare module.exports: $Exports<'amazon-cognito-auth-js/src/CognitoRefreshToken'>;
}
declare module 'amazon-cognito-auth-js/src/CognitoTokenScopes.js' {
  declare module.exports: $Exports<'amazon-cognito-auth-js/src/CognitoTokenScopes'>;
}
declare module 'amazon-cognito-auth-js/src/CookieStorage.js' {
  declare module.exports: $Exports<'amazon-cognito-auth-js/src/CookieStorage'>;
}
declare module 'amazon-cognito-auth-js/src/DateHelper.js' {
  declare module.exports: $Exports<'amazon-cognito-auth-js/src/DateHelper'>;
}
declare module 'amazon-cognito-auth-js/src/index' {
  declare module.exports: $Exports<'amazon-cognito-auth-js/src'>;
}
declare module 'amazon-cognito-auth-js/src/index.js' {
  declare module.exports: $Exports<'amazon-cognito-auth-js/src'>;
}
declare module 'amazon-cognito-auth-js/src/StorageHelper.js' {
  declare module.exports: $Exports<'amazon-cognito-auth-js/src/StorageHelper'>;
}
declare module 'amazon-cognito-auth-js/webpack.config.js' {
  declare module.exports: $Exports<'amazon-cognito-auth-js/webpack.config'>;
}
