// flow-typed signature: 5598b100000d8fd3b9fc4f9cafe2abe4
// flow-typed version: <<STUB>>/big-json_v^3.1.0/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'big-json'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'big-json' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'big-json/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'big-json/lib/index' {
  declare module.exports: $Exports<'big-json/lib'>;
}
declare module 'big-json/lib/index.js' {
  declare module.exports: $Exports<'big-json/lib'>;
}
