// flow-typed signature: a5effe74c506c1425dfe9f361181f4ad
// flow-typed version: <<STUB>>/lodash.orderby_v^4.6.0/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.orderby'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.orderby' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.orderby/index' {
  declare module.exports: $Exports<'lodash.orderby'>;
}
declare module 'lodash.orderby/index.js' {
  declare module.exports: $Exports<'lodash.orderby'>;
}
