// flow-typed signature: 431160a1df2090bca3448d6bf6ef96e0
// flow-typed version: <<STUB>>/s3-upload-stream_v^1.0.7/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   's3-upload-stream'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 's3-upload-stream' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 's3-upload-stream/examples/upload' {
  declare module.exports: any;
}

declare module 's3-upload-stream/lib/s3-upload-stream' {
  declare module.exports: any;
}

declare module 's3-upload-stream/tests/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 's3-upload-stream/examples/upload.js' {
  declare module.exports: $Exports<'s3-upload-stream/examples/upload'>;
}
declare module 's3-upload-stream/lib/s3-upload-stream.js' {
  declare module.exports: $Exports<'s3-upload-stream/lib/s3-upload-stream'>;
}
declare module 's3-upload-stream/tests/test.js' {
  declare module.exports: $Exports<'s3-upload-stream/tests/test'>;
}
