import { SubmissionTypes } from '@oneblink/types'
import { DraftSubmission } from '../src/types/submissions'
import { updateDraft } from '../src/draft-service'

describe('Draft testing', () => {
  const draft: SubmissionTypes.FormsAppDraft = {
    createdAt: '2022-04-12T23:20:55.145Z',
    draftDataId: 'c406f920-6b37-4075-bf6e-d7668ae04275',
    draftId: '446b97e2-8ea9-4344-bfe1-87ca54cc4755',
    externalId: null,
    formId: 5594,
    jobId: null,
    title: 'Library Borrowing Book Form 何',
    updatedAt: '2022-04-13T00:22:52.377Z',
  }
  const draftSubmission: DraftSubmission = {
    formsAppId: 5594,
    submission: {
      Library_Borrowing_System: true,
      User_Email: 'josh@oneblink.io',
      Contact_Number: '0444444443',
      calculation_test: 13,
      testing2: true,
      h1: true,
      h2: true,
      h3: true,
      h4: true,
      h5: true,
    },
    definition: {
      id: 5594,
      name: 'Library Borrowing Book Form 何',
      description: 'This is where you put your name.  寿司 を 食べる',
      organisationId: '61886bb44b5c9b1300000001',
      elements: [
        {
          id: '1ec7ba41-5b27-4583-b8d0-2e55539333f0',
          label: 'wahoo',
          type: 'page',
          conditionallyShow: false,
          requiresAllConditionallyShowPredicates: false,
          elements: [
            {
              name: 'Library_Borrowing_System',
              label: 'Library Borrowing System ماذا',
              type: 'heading',
              id: '7137cb5e-a19c-4fc8-8dd8-53a3b2b55b18',
              conditionallyShow: false,
              headingType: 2,
            },
            {
              name: 'Books_List',
              label: '寿司 を 食べますか',
              type: 'repeatableSet',
              id: 'aa52e01b-c07d-42f1-807e-15433fa5c938',
              conditionallyShow: false,
              elements: [
                {
                  name: 'Book_Title',
                  label: 'Book Title',
                  type: 'text',
                  required: true,
                  id: 'a476e930-6fe7-4adb-96aa-46c3b318e474',
                  conditionallyShow: false,
                  readOnly: false,
                  isDataLookup: false,
                  isElementLookup: false,
                },
                {
                  name: 'Borrowing_Dates',
                  label: 'Borrowing Dates',
                  type: 'date',
                  required: true,
                  id: 'dc56efd9-f810-4671-8306-758973f75204',
                  conditionallyShow: false,
                  readOnly: false,
                  isDataLookup: false,
                  isElementLookup: false,
                  fromDate: 'NOW',
                },
                {
                  name: 'Book_Type',
                  label: 'Book Type',
                  type: 'select',
                  required: true,
                  id: '9682c9dc-0371-4107-b1b8-63e829a66bca',
                  conditionallyShow: false,
                  options: [
                    {
                      id: '0d7e1116-3acc-4adb-ab29-612c0133edf7',
                      label: 'Fiction',
                      value: '0',
                    },
                    {
                      id: '24eb8919-3e12-4eb1-8388-b3c7097c5595',
                      label: 'Non-Fiction',
                      value: '1',
                    },
                  ],
                  hint: 'Select the type of book it is.',
                  readOnly: false,
                  isDataLookup: false,
                  isElementLookup: false,
                  optionsType: 'CUSTOM',
                  conditionallyShowOptions: false,
                  multi: true,
                },
                {
                  name: 'Book_Tracker_Switch',
                  label: 'Book Tracker Switch',
                  type: 'boolean',
                  required: false,
                  id: 'f882bac6-4554-4bc0-9c0c-1bfb82607926',
                  conditionallyShow: false,
                  readOnly: false,
                  isDataLookup: false,
                  isElementLookup: false,
                  defaultValue: false,
                },
                {
                  name: 'Repeateable_Set_Image',
                  label: 'Repeateable Set Image',
                  type: 'files',
                  id: '0accaad7-b1ac-4ea8-98f7-7ed062cb7f84',
                  conditionallyShow: false,
                  storageType: 'private',
                  readOnly: false,
                  restrictFileTypes: false,
                  allowExtensionlessAttachments: false,
                  isDataLookup: false,
                  isElementLookup: false,
                },
              ],
              readOnly: false,
            },
            {
              name: 'User_Email',
              label: 'Email อะไร',
              type: 'email',
              required: true,
              id: '7d0c44f5-4b76-455c-9bac-add09818c3b4',
              conditionallyShow: false,
              hint: 'Please insert your email address here.',
              readOnly: false,
              isDataLookup: false,
              isElementLookup: false,
            },
            {
              name: 'Contact_Number',
              label:
                'All | 全部 | 全て |  бүгд | الكل | את כל | gì | क्या | چی | អ្វី | што | რა | ምንድን | ինչ | কি | ဘာလဲ | τι | શું | ಏನು | 무엇 | ແມ່ນ​ຫຍັງ  | എന്ത് | के | କଣ | څه |  Шта | ڇا | කුමන | என்ன | ఏమి |  کیا | וואס |  ) Elements (phone)',
              type: 'telephone',
              required: true,
              id: 'bf2cbc9d-4152-42cb-b4df-3ed3e00a6567',
              conditionallyShow: false,
              hint: 'This is the number that will be used to contact you, if you do not return the book, we will find you.',
              readOnly: false,
              isDataLookup: false,
              isElementLookup: false,
            },
            {
              name: 'CheckBoxes',
              label: 'How did you get here',
              type: 'checkboxes',
              required: false,
              id: '66483839-f303-4d97-9772-9a90e89650e9',
              conditionallyShow: false,
              readOnly: false,
              isDataLookup: false,
              isElementLookup: false,
              buttons: false,
              optionsType: 'CUSTOM',
              conditionallyShowOptions: false,
              canToggleAll: false,
              options: [
                {
                  id: '52a0506d-fda9-4359-937f-911c62c21818',
                  label: 'Jim the Jim man           ',
                  value: 'jimdaman          ',
                },
                {
                  id: '89ad4bf7-4c5f-4ff9-b233-401f22b63ecd',
                  label: 'asdsasdads',
                  value: 'asdsasdads',
                },
                {
                  id: 'c98d85bd-4c6f-4476-b550-cffa23b7e2ac',
                  label: 'fgsghfd',
                  value: 'fgsghfd',
                },
              ],
            },
            {
              name: 'Photo_Of_Books',
              label: 'Photo Of Books',
              type: 'files',
              id: '0b6e817c-1326-4161-b5ce-14f903a96853',
              conditionallyShow: false,
              storageType: 'private',
              restrictFileTypes: false,
              readOnly: false,
              isDataLookup: false,
              isElementLookup: false,
              allowExtensionlessAttachments: false,
            },
            {
              name: 'abn',
              label: 'ABN',
              type: 'abn',
              required: false,
              id: '4922671b-8345-42a7-a208-a1e0c16b03ae',
              conditionallyShow: false,
              readOnly: false,
              isDataLookup: false,
              isElementLookup: false,
              hint: 'do the work',
              placeholderValue: 'XX-XXX-XXX-XXX',
            },
            {
              name: 'bsb',
              label: 'BSB',
              type: 'bsb',
              required: false,
              id: '22b63664-27c5-4071-9ec6-813c4b78460a',
              conditionallyShow: false,
              readOnly: false,
              isDataLookup: false,
              isElementLookup: false,
            },
            {
              name: 'Testing_Stuff_for_po_boxes',
              label: 'Testing Stuff for po boxes',
              type: 'geoscapeAddress',
              required: false,
              id: 'e57ccd21-8b0e-4f67-ba7a-104847a67a16',
              conditionallyShow: false,
              readOnly: false,
              isDataLookup: false,
              isElementLookup: false,
              stateTerritoryFilter: ['NSW', 'QLD'],
            },
            {
              name: 'testing',
              label: 'testing',
              type: 'barcodeScanner',
              required: false,
              id: 'f949adfd-6f92-4511-adf8-0fc51c963c4e',
              conditionallyShow: false,
              readOnly: false,
              isDataLookup: false,
              isElementLookup: false,
              restrictBarcodeTypes: false,
            },
            {
              name: 'calculation_test',
              label: 'calculation test',
              type: 'calculation',
              id: 'fd6fb067-ef6e-4a8e-9165-ce7b3b05cb3a',
              conditionallyShow: false,
              defaultValue: '{RESULT}',
              calculation: '1+3+6+3',
              displayAsCurrency: true,
            },
            {
              name: 'asdfs',
              label: 'dfssdfsdfdsf',
              type: 'compliance',
              required: false,
              id: '75a80e0c-4004-4d62-a845-14c9c3c6c8f4',
              conditionallyShow: false,
              options: [
                {
                  id: '0d7e1116-3acc-4adb-ab29-612c0133edf7',
                  label: 'Fiction',
                  value: '0',
                },
                {
                  id: '24eb8919-3e12-4eb1-8388-b3c7097c5595',
                  label: 'Non-Fiction',
                  value: '1',
                },
              ],
              storageType: 'private',
              optionsType: 'CUSTOM',
              conditionallyShowOptions: false,
              readOnly: false,
              isDataLookup: false,
              isElementLookup: false,
            },
            {
              name: 'geoscape_lets_go',
              label: 'Geoscape Lets Go',
              type: 'pointAddress',
              required: false,
              id: 'aa7d0006-df30-4470-93f7-7d54bddc9c57',
              conditionallyShow: false,
              readOnly: false,
              isDataLookup: false,
              isElementLookup: false,
            },
            {
              name: '123',
              label: '123',
              type: 'autocomplete',
              required: false,
              id: 'e09f7b76-0ea7-4e84-aaae-ed2f70a6ce43',
              conditionallyShow: false,
              optionsType: 'CUSTOM',
              conditionallyShowOptions: false,
              readOnly: false,
              isDataLookup: false,
              isElementLookup: false,
              options: [
                {
                  id: 'a7e3a98d-a4d0-4337-95a9-3800a7c089b7',
                  label: 'asdf',
                  value: 'asdf',
                },
                {
                  id: '0d4a0e03-90ac-4037-a437-44043a49cff7',
                  label: 'asdfsdaf',
                  value: 'asdfsdaf',
                },
                {
                  id: 'd37673a0-d141-44fe-8fe3-773d4ce08cc3',
                  label: 'asdfs',
                  value: 'asdfs',
                },
                {
                  id: '9683e6e2-d3c4-4640-9e34-20947a69f8eb',
                  label: 'dsa',
                  value: 'dsa',
                },
                {
                  id: '9a917943-63e9-4457-bd55-d0f74cad1ff6',
                  label: 'da',
                  value: 'da',
                },
                {
                  id: '3f132e95-c442-4bdd-955b-0c85ea1930c3',
                  label: 'f',
                  value: 'f',
                },
                {
                  id: '7c9639d8-9ee6-46b7-be49-ec97f705f42b',
                  label: 'f',
                  value: 'fy',
                },
                {
                  id: '7a56fe1a-534d-4e1d-964c-2e3cb6ee7321',
                  label: 'gf',
                  value: 'gf',
                },
                {
                  id: '3a17d740-aa58-47f7-a07d-bf6919d7cea4',
                  label: 'gf',
                  value: 'gk',
                },
                {
                  id: 'c159132e-7a55-4388-99e8-3b2941c9f8a5',
                  label: 'sdg',
                  value: 'sdg',
                },
                {
                  id: '80b5a280-d8dd-457c-be69-a5ab0c5c465e',
                  label: 'dh',
                  value: 'dh',
                },
                {
                  id: 'a4be9482-ca76-4d3f-b76b-88d244b92585',
                  label: 'h',
                  value: 'h',
                },
                {
                  id: '9b713d16-cd53-418c-a384-170ffa3f6fd2',
                  label: 'jhk,k',
                  value: 'jhk,k',
                },
                {
                  id: '4f92ce5f-1e10-4dac-8b80-a92168ab7186',
                  label: 'ewas',
                  value: 'ewas',
                },
                {
                  id: '835692ff-a545-4da8-91e8-5b8b7e812a3f',
                  label: 'gfds',
                  value: 'gfds',
                },
                {
                  id: 'a00efd15-84e2-44bf-add6-67f2429e8695',
                  label: 'sa',
                  value: 'sa',
                },
                {
                  id: '59aa5d3d-f607-4b69-b0e3-a2eb7d471738',
                  label: 'dfgdfs',
                  value: 'asf',
                },
                {
                  id: '98a24589-f1f4-4f6d-affe-ee2a83fe606b',
                  label: 'g',
                  value: 'g',
                },
              ],
            },
            {
              name: 'testing2',
              label: 'testing2',
              type: 'image',
              id: '1b1d4b46-f759-489d-8784-1a95a0687e1d',
              conditionallyShow: false,
              defaultValue:
                'https://s3.ap-southeast-2.amazonaws.com/josh.forms-test.oneblink.io/assets/images/1fff57cc-33de-4768-97b6-fdf27c329ba7/%C2%AE%20%283%29.png',
            },
          ],
        },
        {
          id: '0c7a61e2-e520-42d9-accc-1e6a55c24464',
          label: 'wahey',
          type: 'page',
          conditionallyShow: false,
          requiresAllConditionallyShowPredicates: false,
          elements: [
            {
              name: 'zxsdsd',
              label: 'zxsdsd',
              type: 'text',
              required: false,
              id: 'f40b2307-61db-4bca-842b-5317261b4a1a',
              conditionallyShow: false,
              readOnly: false,
              isDataLookup: false,
              isElementLookup: false,
              regexPattern: '[a-z]*',
              regexMessage: 'Hi',
            },
            {
              name: 'h1',
              label: 'h1',
              type: 'heading',
              id: 'f8768c32-7c60-4038-9217-8e3c517e0d80',
              conditionallyShow: false,
              headingType: 1,
            },
            {
              name: 'h2',
              label: 'h2',
              type: 'heading',
              id: 'a129b6d3-4a42-4d9c-bcec-189202cf3ea7',
              conditionallyShow: false,
              headingType: 2,
            },
            {
              name: 'h3',
              label: 'h3',
              type: 'heading',
              id: '7674d9b6-18e8-44ad-9028-8941c28c0c59',
              conditionallyShow: false,
              headingType: 3,
            },
            {
              name: 'h4',
              label: 'h4',
              type: 'heading',
              id: 'aa9199d8-3ab9-4705-8cea-07332c60eb8c',
              conditionallyShow: false,
              headingType: 4,
            },
            {
              name: 'h5',
              label: 'h5',
              type: 'heading',
              id: '763cc264-5beb-4368-9625-493fe65a14f5',
              conditionallyShow: false,
              headingType: 5,
            },
          ],
        },
        {
          id: '0427ca7c-b843-4e1f-a359-3ee06c42c9b8',
          label: 'wahee',
          type: 'page',
          conditionallyShow: false,
          requiresAllConditionallyShowPredicates: false,
          elements: [
            {
              name: 'mnbkknjkkj',
              label: 'mnb,k,knjkkj',
              type: 'number',
              required: false,
              id: 'd1af2136-4e6d-499c-be4c-8ae6ce947e5c',
              conditionallyShow: false,
              readOnly: false,
              isDataLookup: false,
              isElementLookup: false,
              isSlider: false,
              isInteger: false,
            },
          ],
        },
      ],
      isAuthenticated: true,
      draftEvents: [
        {
          type: 'PDF',
          configuration: {
            email: 'josh@oneblink.io',
            emailSubjectLine: 'testing but just email but draft',
            pdfFileName: 'Testing Fun',
            excludedElementIds: [],
          },
          conditionallyExecute: false,
          requiresAllConditionallyExecutePredicates: false,
        },
      ],
      schedulingEvents: [],
      paymentEvents: [],
      submissionEvents: [],
      approvalEvents: [],
      createdAt: '2021-11-08T00:19:28.000Z',
      updatedAt: '2022-04-11T05:43:42.000Z',
      isMultiPage: true,
      postSubmissionAction: 'FORMS_LIBRARY',
      cancelAction: 'FORMS_LIBRARY',
      isInfoPage: false,
      formsAppEnvironmentId: 157,
      tags: ['aaaaaa'],
      formsAppIds: [1733, 2133],
    },
  }
  updateDraft(draft, draftSubmission)
  expect(draft.createdAt).toContainEqual('2022-04-12T23:20:55.145Z')
})
